// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyMJIfviMN8ei7Lrx4SY8NYpAXjAvwx80',
    appId: '1:992029478706:web:094c3a6283b43696c4112b',
    messagingSenderId: '992029478706',
    projectId: 'laza-b237e',
    authDomain: 'laza-b237e.firebaseapp.com',
    storageBucket: 'laza-b237e.firebasestorage.app',
    measurementId: 'G-LEEFJFLHB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo8zd-buh0n4v4al9Y5IZN6pDcOan9rcw',
    appId: '1:992029478706:android:3c867d73529fcf42c4112b',
    messagingSenderId: '992029478706',
    projectId: 'laza-b237e',
    storageBucket: 'laza-b237e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCihZAHcRxrRFG7pUIlO72naxkrvetKwM',
    appId: '1:992029478706:ios:de9fdb930ce3ec3bc4112b',
    messagingSenderId: '992029478706',
    projectId: 'laza-b237e',
    storageBucket: 'laza-b237e.firebasestorage.app',
    iosBundleId: 'com.example.laza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCihZAHcRxrRFG7pUIlO72naxkrvetKwM',
    appId: '1:992029478706:ios:de9fdb930ce3ec3bc4112b',
    messagingSenderId: '992029478706',
    projectId: 'laza-b237e',
    storageBucket: 'laza-b237e.firebasestorage.app',
    iosBundleId: 'com.example.laza',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyMJIfviMN8ei7Lrx4SY8NYpAXjAvwx80',
    appId: '1:992029478706:web:16a1f3ae2015ef1ac4112b',
    messagingSenderId: '992029478706',
    projectId: 'laza-b237e',
    authDomain: 'laza-b237e.firebaseapp.com',
    storageBucket: 'laza-b237e.firebasestorage.app',
    measurementId: 'G-PXTTGPSJ2L',
  );
}
